name: ${project.name}
version: ${project.version}
main: eu.kennytv.serverlistmotd.spigot.ServerListMotdSpigotBase
author: KennyTV
softdepend: [ProtocolLib]
website: https://www.spigotmc.org/resources/57851

commands:
  serverlistmotdspigot:
    description: ServerListMotd main-command
    aliases: [serverlistmotd, motd]